from cs_common import build_cheatsheet

S = [
 ("The flow model", [
    ("Trigger","The 'when' — exactly one per flow."),
    ("Action","The 'then' — runs top to bottom."),
    ("Connector","Bundle of triggers/actions for a service."),
    ("Dynamic content","Output of one step used in a later one."),
    ("Expression","Functions for when dynamic content isn't enough."),
 ]),
 ("Flow types", [
    ("Automated","Starts on an event (email, item changed)."),
    ("Instant","You start it (button / Teams / Power Apps)."),
    ("Scheduled","Runs on a clock (Recurrence trigger)."),
    ("Desktop (RPA)","Drives the screen when there's no API."),
 ]),
 ("Controls", [
    ("Condition","If / else — Yes and No branches."),
    ("Switch","Branch on one value's cases + default."),
    ("Apply to each","Loop over an array."),
    ("Do until","Loop until a condition is true (set a limit)."),
    ("Scope","Group actions (wrap error handling)."),
    ("Terminate","End the run with a status."),
 ]),
 ("Referencing data", [
    ("Dynamic content","Pick a previous step's output from the list."),
    ("@{ … }","Expression inside text/JSON."),
    ("?['name']","Safe-read a property (no error if missing)."),
    ("Whole expression","Switch the field to expression mode, type a function."),
 ]),
 ("Reference functions", [
    ("triggerBody()?['Subject']","A field from the trigger."),
    ("triggerOutputs()","The full trigger output."),
    ("body('List_rows')?['value']","Output of a named action."),
    ("outputs('Compose')","Output of a Compose/action."),
    ("items('Apply_to_each')","Current loop item."),
    ("variables('Total')","A variable's value."),
    ("item()?['Priority']","Current item in Filter array."),
 ]),
 ("String functions", [
    ("concat(a, b, …)","Join strings."),
    ("substring(s, start, len)","Slice text."),
    ("replace(s, old, new)","Swap text."),
    ("toUpper(s) / toLower(s)","Change case."),
    ("trim(s) · length(s)","Strip spaces · count chars."),
    ("split(s, ',')","Text to an array."),
    ("indexOf(s, 'x')","Position (-1 if absent)."),
    ("startsWith / endsWith(s, x)","True/false test."),
    ("guid()","A new unique id."),
 ]),
 ("Collection functions", [
    ("length(arr)","How many items."),
    ("first(arr) / last(arr)","Edge items."),
    ("take(arr, n) / skip(arr, n)","Slice an array."),
    ("contains(arr, x)","Membership test."),
    ("empty(arr)","True if empty/null."),
    ("join(arr, ', ')","Array to a string."),
    ("union / intersection(a, b)","Combine / overlap."),
 ]),
 ("Logic &amp; comparison", [
    ("equals(a, b)","a = b."),
    ("greater / less(a, b)","a &gt; b / a &lt; b."),
    ("greaterOrEquals / lessOrEquals","a &gt;= b / a &lt;= b."),
    ("and(x, y) / or(x, y)","Combine booleans."),
    ("not(x)","Negate."),
    ("if(test, yes, no)","Inline branch."),
    ("coalesce(a, b)","First non-null."),
 ]),
 ("Conversion", [
    ("int(x) / float(x)","Text to number."),
    ("string(x)","Anything to text."),
    ("bool(x)","To true/false."),
    ("json(x)","Parse a JSON string to an object."),
    ("array(x) / createArray(a,b)","Make an array."),
    ("base64(s) / base64ToString(s)","Encode / decode."),
 ]),
 ("Math", [
    ("add / sub(a, b)","a + b / a - b."),
    ("mul / div(a, b)","a * b / a / b."),
    ("mod(a, b)","Remainder."),
    ("min / max(a, b)","Smallest / largest."),
    ("rand(a, b)","Random integer in a range."),
 ]),
 ("Date &amp; time", [
    ("utcNow()","Current UTC timestamp."),
    ("addDays(d, 7) / addHours(d, 2)","Shift a date."),
    ("formatDateTime(d, 'dd/MM/yyyy')","Format a date."),
    ("convertTimeZone(d, src, dst, fmt)","Change time zone."),
    ("startOfDay(d) / startOfMonth(d)","Truncate."),
    ("dayOfWeek(d) · ticks(d)","Weekday num · sortable number."),
 ]),
 ("Null &amp; safe access", [
    ("?['field']","Read without erroring on null."),
    ("coalesce(x, 'n/a')","Default when null."),
    ("empty(x)","True for null / '' / []."),
    ("if(empty(x), …, …)","Guard against missing data."),
 ]),
 ("Array actions", [
    ("Filter array","Keep items matching a condition."),
    ("Select","Reshape items to new keys."),
    ("Create HTML table","Array to a table (for emails)."),
    ("Join","Array to a delimited string."),
    ("Compose","Hold/inspect any value."),
 ]),
 ("OData Filter Query", [
    ("Status eq 'On Hold'","Equals (text in single quotes)."),
    ("Priority eq 'High' and …","Combine with and / or."),
    ("Revenue gt 20000","gt ge lt le ne."),
    ("startswith(Title,'GOLD')","Function filters."),
    ("Use it on","List rows / Get items — filter at source."),
 ]),
 ("Variables", [
    ("Initialize variable","Once, at the top (name, type, value)."),
    ("Set variable","Replace the value."),
    ("Increment variable","Add to a number."),
    ("Append to array/string","Build up a collection or text."),
    ("Tip","Init outside loops; set/append inside."),
 ]),
 ("Approvals", [
    ("Start and wait for an approval","Pause until a decision."),
    ("Approve/Reject — First to respond","Common type."),
    ("outcome","'Approve' or 'Reject'."),
    ("responses","Comments &amp; approver details."),
 ]),
 ("Error handling", [
    ("Configure run after","Run a step on failure/timeout/skip."),
    ("Scope: Try / Catch","Group steps; next Scope runs 'has failed'."),
    ("result('Try')","Details of steps in a scope."),
    ("Terminate","End with Failed + a message."),
    ("Retry policy","Set on an action's settings."),
 ]),
 ("HTTP &amp; JSON (premium)", [
    ("HTTP","Call any REST API (premium connector)."),
    ("Parse JSON","Turn a response into usable fields."),
    ("Generate schema","From a sample payload."),
    ("body('HTTP')?['id']","Read a field from the response."),
 ]),
 ("Triggers &amp; conditions", [
    ("Trigger condition","Only start when an expression is true."),
    ("@equals(triggerBody()?['Status'],'On Hold')","Example trigger condition."),
    ("Split On","Debatch an array trigger into runs."),
    ("Concurrency","Control parallel trigger runs."),
 ]),
 ("Common patterns", [
    ("Notify on change","Trigger filter &gt; Condition &gt; Post to Teams."),
    ("Weekly digest","Recurrence &gt; List rows &gt; HTML table &gt; email."),
    ("Escalate","Condition High &gt; Approval &gt; update item."),
    ("No-API portal","Desktop flow (RPA) drives the UI."),
    ("Poll a status","Do until status = Closed (with delay)."),
 ]),
 ("Gotchas", [
    ("Loops are slow","Filter before Apply to each; use concurrency."),
    ("Missing dynamic value","Producing step is below / in another branch."),
    ("Null fields","Use ?['x'] and coalesce()."),
    ("Times are UTC","Convert before formatting for users."),
    ("Filter at source","OData query beats looping + Condition."),
 ]),
 ("Productivity", [
    ("Peek code","See a step's raw JSON (… menu)."),
    ("Static result","Test a flow without calling services."),
    ("Run history","Inspect each run's inputs/outputs."),
    ("Save as / Export","Reuse a flow as a template."),
    ("Comments","Document tricky steps for the next person."),
 ]),
]

build_cheatsheet(
    "/mnt/user-data/outputs/Power-Automate-Cheat-Sheet.pdf",
    "Power Automate Cheat Sheet",
    "Flows, controls & expressions  ·  DPM Learning Hub",
    S,
    accent="#1D4ED8", code_border="#1D4ED8", code_bg="#EEF2FF",
    code_ink="#1E3A8A", line="#DBE3FF", band_title_color="#FFFFFF",
    footer_label="DPM Learning Hub — Power Automate track",
    intro="A printable reference for building flows and writing expressions in Power Automate. "
          "Trigger = when, actions = then; everything else makes the 'then' smarter. Use ?['field'] to read safely.")
